import Head from "next/head";
import Image from "next/image";
import {
  Navbar,
  About,
  Trial,
  Education,
  Skills,
  Projects,
  Experience,
  Contact,
} from "@/components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section className="flex flex-col">
          <Navbar />
          <About />
          <Skills />
          <Projects />
          <Education />
          <Experience />
          <Contact />
          {/* <Trial /> */}
        </section>
      </main>
    </>
  );
}
